### PR TITLE
ReflexRave: A movie recommendation system

### PR DESCRIPTION
**Pull request by HeetVekariya**
# Submission category: AI apps

<br>

# ReflexRave
- ReflexRave is a movie recommendation system powered by machine learning, trained on the TMDB dataset of 5000 movies.
- The app is built using **`python`** and **`Reflex`** framework and uses `TMDB` API to fetch the movie data.

<br>

# Look and Feel
Screenshot from 2023-10-22 12-35-50
Screenshot from 2023-10-22 12-33-53

### CODE REVIEW

**Comment by picklelo** [comment]
This looks awesome! I'm not able to run it locally as it's missing the `movie_dict.pkl` file - could you add that file to the submission? Would love to get this app deployed and shared on our gallery as well - excited to try it out!

**Comment by HeetVekariya** [comment]
Loved to hear that, I will upload the .pkl file asap by today

**Review by picklelo — APPROVED** [review]
Awesome work! Was able to get the app running smoothly in the end. Will reach out to you to host this app on our service as well if you're interested!

**Comment by HeetVekariya** [comment]
> Awesome work! Was able to get the app running smoothly in the end. Will reach out to you to host this app on our service as well if you're interested!

Thank you for merging it 😊, i am interested ✋

**Pull request merged**
