### PR TITLE
text summarizer app

### PR DESCRIPTION
**Pull request by emmakodes**
I created this text summarizer app that enables users to input a text then Openai llm and langchain will generate a summary of the text. You can see more of the project here: [https://github.com/emmakodes/text_summarizer]

This app is under ai_apps category

You can read the article where I explained how I built the app: [Build a Text Summarization app using Reflex (Pure Python)](https://dev.to/emmakodes_/build-a-text-summarization-app-using-reflex-pure-python-1a94)

app repo: https://github.com/emmakodes/text_summarizer

firstpage

### CODE REVIEW

**Review by picklelo — COMMENTED** [review]
Thanks for submitting! Looks like the repo is missing a `requirements.txt` as I was following the instructions in the README, could you add that?

**Comment by emmakodes** [comment]
Okay, thanks @picklelo I have just added it.

**Comment by emmakodes** [comment]
@picklelo Can I also make a pull request for the Ocr web app I built? https://github.com/emmakodes/reflex_ocr_system

**Comment by emmakodes** [comment]
I added a chatbot under interactive_db category that enables users to interact with their dataframe without using code but natural language.

The following is the output of the app

dataframechat

**Comment by emmakodes** [comment]
I added a reflex ocr app under miscellaneous category that enables users to upload an image then the app extracts the text of the image to output to the user.

This app idea is brought out of the fact that sometimes I would want to use the text of an image but I don't want to type the text all over so I can just use this solution to extract the text of the image.

You can the article where I explained how I built the app: [Build an OCR app using fullstack Python Framework Reflex](https://dev.to/emmakodes_/build-an-ocr-app-using-fullstack-python-framework-reflex-4ao7)

app repo:  https://github.com/emmakodes/reflex_ocr_system

**Review by picklelo — APPROVED** [review]
Awesome work! All three submissions are very impressive, I really liked the database summarizer app. These would be awesome to feature on our gallery as well. 

Will reach out shortly regarding the prizes :)

**Pull request merged**
