### PR TITLE
Submission : ai_apps, Project name : Mushroom Classification analysis

### PR DESCRIPTION
**Pull request by samrat2k03**
Mushroom classification analysis project comes unders ai_apps project submission , 
Could you kindly provide some feedback.

### CODE REVIEW

**Comment by Alek99** [comment]
Hello cool project! All projects must be made in Reflex tough in order to qualify for the hackathon, I'll make this more clear in the readme.

**Comment by samrat2k03** [comment]
Ok 👍

**Comment by Alek99** [comment]
If you can convert your frontend to Reflex this project will be eligible in the AI category.

**Comment by samrat2k03** [comment]
> If you can convert your frontend to Reflex this project will be eligible in the AI category.

Is there any resources available ?

**Comment by Alek99** [comment]
> > If you can convert your frontend to Reflex this project will be eligible in the AI category.
> 
> Is there any resources available ?

https://reflex.dev

**Comment by samrat2k03** [comment]
im facing problem in my project ,cannot initialize the reflex ```reflex init``` , after i add the path in environmental variable ...
everytime it shows like : 
```
C:\Users\samra>reflex --version
'reflex' is not recognized as an internal or external command,
operable program or batch file.`
```
and i tried to reinstalled package and restart the pc

**Comment by ElijahAhianyo** [comment]
> 'reflex' is not recognized as an internal or external command,

can you try installing reflex in a virtual environment?

**Comment by picklelo** [comment]
Closing this as is isn't using Reflex - feel free to share a Reflex example if you have it ready!

**Pull request closed without merging**
